# Vue Dockerfile
FROM node:16 AS build

WORKDIR /app/frontend

# 複製 package.json 和 package-lock.json
COPY frontend/package*.json ./

# 安裝 Node.js 依賴
RUN npm install

# 複製前端文件並建構
# COPY <源路径> <目标路径>
COPY frontend /app/frontend

# 讓vue的修可以直接在docker container響應
ENV CHOKIDAR_USEPOLLING=true

# ==== 開發模式 Start ==== 
EXPOSE 8080
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
# ==== 開發模式 End ==== 


# ==== 生產模式 End ==== 
# # 在/app下生成dist目錄
# RUN npm run build

# # 使用 Nginx 提靜態文件服務
# FROM nginx:alpine

# # 複製自定義 Nginx 配置文件到容器中
# COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/frontend/dist /usr/share/nginx/html

# # Expose Nginx port
# EXPOSE 80
# ==== 生產模式 End ==== 


