# Vue Dockerfile prob
FROM node:16 AS build

WORKDIR /frontend

# 複製 package.json 和 package-lock.json
COPY frontend/package*.json ./

# 安裝 Node.js 依賴
RUN npm install

# 複製前端文件並建構
# COPY <源路径> <目标路径>
COPY frontend .

# 在生成dist目錄
RUN npm run build

# 安装 http-server
RUN npm install -g http-server

WORKDIR /frontend/dist

# 使用 http-server 運行 Vue 
CMD ["http-server", "-p", "8080"]

# # 使用 Nginx 提靜態的文件服務
# FROM nginx:alpine

# # 複製自定義 Nginx 配置文件到容器中
# COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/frontend/dist /usr/share/nginx/html

# Expose Nginx port
# EXPOSE 80


